
`ifndef MXINT8_INCLUDES

`define MXINT8_INCLUDES

`include "mx_general_includes.v"

`define MXINT8_ELEMENT_SIGN_BIT 7
`define MXINT8_ELEMENT_VALUE_BITS 6:0

parameter MXINT8_ELEMENT_WIDTH = 8;
parameter MXINT8_ELEMENT_IMPLICIT_SCALE_LOG2 = -6;

`endif // MXINT8_INCLUDES