
`ifndef SCALAR_INCLUDES

`define SCALAR_INCLUDES

`define FLOAT32_SIGN_BIT 31
`define FLOAT32_EXPONENT_BITS 30:23
`define FLOAT32_MANTISSA_BITS 22:0

parameter FLOAT32_WIDTH = 32;
parameter FLOAT32_EXPONENT_WIDTH = 8;
parameter FLOAT32_MANTISSA_WIDTH = 23;

`endif // SCALAR_INCLUDES