
`ifndef SCALAR_INCLUDES

`define SCALAR_INCLUDES

`define FLOAT32_WIDTH 32

`define FLOAT32_SIGN_BIT 31

`define FLOAT32_MANTISSA_MSB 22
`define FLOAT32_MANTISSA_LSB 0
`define FLOAT32_MANTISSA_BITS `FLOAT32_MANTISSA_MSB:`FLOAT32_MANTISSA_LSB
`define FLOAT32_MANTISSA_WIDTH 23

`define FLOAT32_EXPONENT_MSB 30
`define FLOAT32_EXPONENT_LSB 23
`define FLOAT32_EXPONENT_BITS `FLOAT32_EXPONENT_MSB:`FLOAT32_EXPONENT_LSB
`define FLOAT32_EXPONENT_WIDTH 8

`define FLOAT32_MANTISSA_MXINT8_MSB `FLOAT32_MANTISSA_MSB
`define FLOAT32_MANTISSA_MXINT8_LSB 17
`define FLOAT32_MANTISSA_MXINT8_BITS `FLOAT32_MANTISSA_MXINT8_MSB:`FLOAT32_MANTISSA_MXINT8_LSB

`endif // SCALAR_INCLUDES